const WS_EVENTS = {
  HELLO: "HELLO",
  PING: "PING",
  PONG: "PONG",
  USER: {
    DELETE_SENT_FRIEND_REQUEST: "DELETE_SENT_FRIEND_REQUEST",
    ADD_RECEIVED_FRIEND_REQUEST: "ADD_RECEIVED_FRIEND_REQUEST",
    DELETE_RECEIVED_FRIEND_REQUEST: "DELETE_RECEIVED_FRIEND_REQUEST",
    ADD_FRIEND: "ADD_FRIEND",
    DELETE_FRIEND: "DELETE_FRIEND",
    ADD_BLOCKER: "ADD_BLOCKER",
    DELETE_BLOCKER: "DELETE_BLOCKER",
    SUBSCRIBE_CHANNEL: "SUBSCRIBE_CHANNEL",
    UNSUBSCRIBE_CHANNEL: "UNSUBSCRIBE_CHANNEL",
    ADD_CHANNEL: "ADD_CHANNEL"
  },
  CHANNEL: {
    SET_FRIEND_ONLINE: "SET_FRIEND_ONLINE",
    SET_FRIEND_OFFLINE: "SET_FRIEND_OFFLINE",
    DELETE_FRIEND: "DELETE_FRIEND",
    UPDATE_CHANNEL: "UPDATE_CHANNEL",
    DELETE_CHANNEL: "DELETE_CHANNEL",
    ADD_MEMBER: "ADD_MEMBER",
    ADD_MEMBERS: "ADD_MEMBERS",
    DELETE_MEMBER: "DELETE_MEMBER",
    ADD_ADMIN: "ADD_ADMIN",
    DELETE_ADMIN: "DELETE_ADMIN",
    ADD_BAN: "ADD_BAN",
    DELETE_BAN: "DELETE_BAN",
    ADD_MESSAGE: "ADD_MESSAGE",
    DELETE_MESSAGE: "DELETE_MESSAGE",
    ADD_POST: "ADD_POST",
    DELETE_POST: "DELETE_POST",
    ADD_POST_LIKE: "ADD_POST_LIKE",
    DELETE_POST_LIKE: "DELETE_POST_LIKE",
    ADD_COMMENT: "ADD_COMMENT",
    DELETE_COMMENT: "DELETE_COMMENT",
    ADD_COMMENT_LIKE: "ADD_COMMENT_LIKE",
    DELETE_COMMENT_LIKE: "DELETE_COMMENT_LIKE",
    ADD_VIEWER: "ADD_VIEWER",
    DELETE_VIEWER: "DELETE_VIEWER"
  },
  USER_CHANNEL: {
    JOIN_CHANNEL: "JOIN_CHANNEL",
    LEAVE_CHANNEL: "LEAVE_CHANNEL",
    BEFRIEND: "BEFRIEND",
    UNFRIEND: "UNFRIEND",
    BLOCK_FRIEND: "BLOCK_FRIEND"
  },
  USERS_CHANNELS: {
    UPDATE_USER: "UPDATE_USER"
  },
  VIDEO_CONTROL: {
    ADD_VIDEO: "ADD_VIDEO",
    DELETE_VIDEO: "DELETE_VIDEO",
    REORDER_QUEUE: "REORDER_QUEUE"
  }
};

module.exports = {
  WS_EVENTS
};
